
[window]
decorations = "full"
decorations_theme_variant = "dark"
option_as_alt = "Both"

[font]
normal.family = "Hack Nerd Font"
bold.family = "Hack Nerd Font"
italic.family = "Hack Nerd Font"
bold_italic.family = "Hack Nerd Font"
size = 14

[general]
import = ["./themes/tokyo-night-storm.toml"]
