{inputs, pkgs, ...}: {
  environment.systemPackages = with pkgs; [
    neovim
    go
    inputs.neovim-nightly-overlay.packages.${pkgs.system}.default
    nodejs_24
    pnpm
    groovy
    ruby
    vim
    lazygit
    pre-commit
    zulu23
    dbeaver-bin
    libpq
    postgresql
    lazysql
    gh
    google-cloud-sdk
    awscli2
    pipx
    nil
    nixfmt-rfc-style
    cyberduck
    zed-editor
    wezterm
    rustc
    cargo
    feedr
    opentofu
  ];
}
